### PR TITLE
Fixed lint issues and made facebook work

### LINKED ISSUE #3: Custom Lambda Authorizer - Facebook Identity Provider Configuration for Expanse LLC
Token retrieved from Facebook ID Provider needs to be verified by the Lambda Authorizer and the principalId returned.

FacebookIdModule.js returns a 0 or a principalId to the AuthorizerModule.js class

### PR DESCRIPTION
**Pull request by ryanwscott**
Resolves #3 #6

### CODE REVIEW

**Comment by mle6366** [comment]
@ryanwscott Did you do an integration test?

**Comment by ryanwscott** [comment]
@mle6366 I updated the PR with fixes for deployment and integration testing.

File: config/ProviderConfig.js [hunk 1]
```diff
@@ -0,0 +1,46 @@
+'use strict';
+
+class ProviderConfig {
+  constructor() {
+    this.google = {
```
Comment (mle6366) [inline config/ProviderConfig.js:5]: I really wanted these to be versioned, as these providers seem to upgrade their OAuth endpoints regularly with versioning. It would be easy to have the google:{ v3:{} } object for instance, and then just add v4 support later down the line while keeping backwards compatibility. What do you think?
